/* 
Developed By:
https://github.com/metalhead13
*/




 SELECT DISTINCT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.CERTIFICADO, 
          /* LLAVE_COD */
            CONCAT(ramo_prod, '_', cod_producto) AS LLAVE_COD, 
          t1.TIPO_TRANSAC, 
		  t1.SBU AS SBU_ANT,
          t1.TIPO_POLIZA, 
          /* LLAVE_TIPO */
            CONCAT(RAMO_PROD,'_', TIPO_POLIZA) AS LLAVE_TIPO, 
          /* LLAVE_PROD */
            CONCAT(RAMO_PROD,'_', POLIZA, '_', certificado) AS LLAVE_PROD
INTO #DWH_POLIZAS_H
      FROM "PROD"."DWH_POLIZAS_H" t1
      WHERE t1.PERIODO_CONTABLE IN 
           (
           202112
           ) AND t1.TIPO_TRANSAC IN 
           (
           1,
           2,
           4
           ) ;


SELECT PERIODO_CONTABLE, 
          RAMO_PROD, 
          POLIZA, 
          CERTIFICADO, 
          LLAVE_COD, 
          TIPO_TRANSAC, 
          SBU_ANT, 
          TIPO_POLIZA, 
          LLAVE_TIPO, 
          LLAVE_PROD
INTO #QUERY_FOR_DWH_POLIZAS_H 
      FROM #DWH_POLIZAS_H
      WHERE SBU_ANT NOT IN('AUT','SOA','OTH','BON') or SBU_ANT is null;
	  
	  
   SELECT t1.PERIODO_CONTABLE,
T1.LLAVE_COD, 
T1.LLAVE_TIPO,
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.CERTIFICADO, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC,
		  T1.TIPO_POLIZA,
		  t2.APLICATIVO, 
          t2.SBU
INTO #BASE_MARCA
      FROM #QUERY_FOR_DWH_POLIZAS_H t1
LEFT JOIN #RAMOS_PROD t2 ON (t1.RAMO_PROD=t2.RAMO_PROD);


SELECT *
INTO #BASE_MARCA_11
FROM #BASE_MARCA;

UPDATE #BASE_MARCA_11 SET SBU = '7150 - Individual Health, Dental, Disability' WHERE LLAVE_TIPO IN ('ACS_I','ADU_I','CAN_I','CCP_I','E1_I','H1_I','O10_I','RDH_I','SE_I','T1_I','Z1_I','LMP_I');


   SELECT PERIODO_CONTABLE, 
          RAMO_PROD, 
          POLIZA, 
          CERTIFICADO, 
          LLAVE_PROD, 
          TIPO_TRANSAC, 
          APLICATIVO, 
          SBU
INTO #BASE_MARCA_2
      FROM #BASE_MARCA_11
      WHERE APLICATIVO IS NOT NULL AND SBU IN(
'7110 - Group Life',
'8600 - Personal Accident',
'7120 - Group Health, Dental, Disability',
'7150 - Individual Health, Dental, Disability'
);


SELECT DISTINCT SBU
INTO #QUERY_FOR_BASE_MARCA_11
FROM #BASE_MARCA_11;


select * from  #BASE_MARCA_2


   SELECT DISTINCT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.CERTIFICADO, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC, 
          t1.APLICATIVO, 
          t1.SBU
INTO #OLD_CORE
      FROM #BASE_MARCA_2 t1
      WHERE t1.APLICATIVO = 'O';
	  


   SELECT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC, 
          t1.APLICATIVO, 
          t1.SBU
INTO #OLD_NUEVOS
      FROM #OLD_CORE t1
      WHERE t1.TIPO_TRANSAC = 1;
	  
SELECT t1.SBU, 
          /* COUNT_DISTINCT_of_LLAVE_PROD */
            (COUNT(DISTINCT(t1.LLAVE_PROD))) AS COUNT_DISTINCT_of_LLAVE_PROD
INTO #QUERY_FOR_OLD_NUEVOS
      FROM #OLD_NUEVOS t1
      GROUP BY t1.SBU;
	  
	 
	 
SELECT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC, 
          t1.APLICATIVO, 
          t1.SBU
INTO #OLD_RENOVADOS
      FROM #OLD_CORE t1
      WHERE t1.TIPO_TRANSAC = 2;
	  
	  
	  
SELECT t1.SBU, 
          /* COUNT_DISTINCT_of_LLAVE_PROD */
            (COUNT(DISTINCT(t1.LLAVE_PROD))) AS COUNT_DISTINCT_of_LLAVE_PROD
INTO #QUERY_FOR_OLD_RENOVADOS
      FROM #OLD_RENOVADOS t1
      GROUP BY t1.SBU;
	  
	  
SELECT DISTINCT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.CERTIFICADO, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC, 
          t1.APLICATIVO, 
          t1.SBU
INTO #OLD_CANCELADOS
      FROM #OLD_CORE t1
      WHERE t1.TIPO_TRANSAC = 4;
	  

SELECT DISTINCT 
          t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC,
		  t1.APLICATIVO, 
          t1.SBU,
		  MAX(T2.TIPO_TRANSAC) AS TIPO_CANCEL
INTO #OLD_CANCELADOS_TIPO
FROM #OLD_CANCELADOS t1
LEFT JOIN "PROD"."DWH_POLIZAS_H" t2 ON(t1.RAMO_PROD = t2.RAMO_PROD AND t1.POLIZA = t2.POLIZA)
WHERE t2.TIPO_TRANSAC IN(1,2) AND t2.PERIODO_CONTABLE>201712
GROUP BY t2.RAMO_PROD,t2.POLIZA,
          t1.PERIODO_CONTABLE, t1.RAMO_PROD,t1.POLIZA, t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC,
		  t1.APLICATIVO, 
          t1.SBU ;


SELECT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.CERTIFICADO, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC, 
          t1.APLICATIVO, 
          t1.SBU
INTO #NEW_CORE
      FROM #BASE_MARCA_2 t1
      WHERE t1.APLICATIVO = 'N';
	  
	  
	  
SELECT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.CERTIFICADO, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC, 
          t1.APLICATIVO, 
          t1.SBU
INTO #NEW_NUEVOS
      FROM #NEW_CORE t1
      WHERE t1.TIPO_TRANSAC = 1;
	  
	  
	  
SELECT t1.SBU, 
          /* COUNT_DISTINCT_of_LLAVE_PROD */
            (COUNT(DISTINCT(t1.LLAVE_PROD))) AS COUNT_DISTINCT_of_LLAVE_PROD
INTO #QUERY_FOR_NEW_NUEVOS
      FROM #NEW_NUEVOS t1
      GROUP BY t1.SBU;
	  
	  
	  
SELECT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.CERTIFICADO, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC, 
          t1.APLICATIVO, 
          t1.SBU
INTO #NEW_RENOVADOS
      FROM #NEW_CORE t1
      WHERE t1.TIPO_TRANSAC = 2;
	  
	  
	  
SELECT t1.SBU, 
          /* COUNT_DISTINCT_of_LLAVE_PROD */
            (COUNT(DISTINCT(t1.LLAVE_PROD))) AS COUNT_DISTINCT_of_LLAVE_PROD
INTO #QUERY_FOR_NEW_RENOVADOS
      FROM #NEW_RENOVADOS t1
      GROUP BY t1.SBU;
	  
	  
SELECT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.CERTIFICADO, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC, 
          t1.APLICATIVO, 
          t1.SBU
INTO #NEW_CANCELADOS
      FROM #NEW_CORE t1
      WHERE t1.TIPO_TRANSAC = 4;
	  
	  
	  
SELECT DISTINCT  
          t1.RAMO_PROD, 
          t1.POLIZA ,
MAX(T1.TIPO_TRANSAC) AS TIPO_CANCEL 
INTO #TIPO_TRANS_NEW
from "PROD"."DWH_POLIZAS_H" T1 WHERE T1.TIPO_TRANSAC IN(1,2) AND T1.PERIODO_CONTABLE>201712
group by t1.ramo_prod,t1.poliza; 



SELECT DISTINCT t1.PERIODO_CONTABLE, 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          t1.LLAVE_PROD, 
          t1.TIPO_TRANSAC,
		  t1.APLICATIVO, 
          t1.SBU,
		  T2.TIPO_CANCEL
INTO #NEW_CANCELADOS_TIPO
      FROM #NEW_CANCELADOS t1
LEFT JOIN #TIPO_TRANS_NEW T2 ON (t1.RAMO_PROD=t2.RAMO_PROD AND t1.POLIZA=t2.POLIZA);


SELECT *
INTO #NUEVOS_TOTAL_B 
FROM #QUERY_FOR_OLD_NUEVOS
UNION
SELECT * FROM #QUERY_FOR_NEW_NUEVOS;


SELECT SBU, 
          /* NUEVOS */
       SUM(COUNT_DISTINCT_of_LLAVE_PROD) AS NUEVOS
INTO #NUEVOS_TOTAL
FROM #NUEVOS_TOTAL_B 
GROUP BY SBU;



SELECT *
INTO #RENOVADOS_TOTALB 
FROM #QUERY_FOR_OLD_RENOVADOS
UNION
SELECT * FROM #QUERY_FOR_NEW_RENOVADOS;


SELECT t1.SBU, 
          /* NUEVOS */
        SUM(t1.COUNT_DISTINCT_of_LLAVE_PROD) AS RENOVADOS
INTO #RENOVADOS_TOTAL
      FROM #RENOVADOS_TOTALB t1

GROUP BY t1.SBU;

SELECT *
INTO #CANCELADOS_TOTALB
FROM #OLD_CANCELADOS_TIPO
UNION
SELECT * FROM #NEW_CANCELADOS_TIPO;


SELECT t1.TIPO_CANCEL, 
          t1.SBU, 
          /* CANCELADOS */
           COUNT(DISTINCT(t1.LLAVE_PROD)) AS CANCELADOS
INTO #CANCELADOS_TOTAL
      FROM #CANCELADOS_TOTALB t1
      GROUP BY t1.TIPO_CANCEL,
               t1.SBU;
			   
SELECT t1.LLAVE_PROD, 
          /* COUNT_of_LLAVE_PROD */
            (COUNT(t1.LLAVE_PROD)) AS COUNT_of_LLAVE_PROD
INTO #QUERY_FOR_NEW_CANCELADOS
      FROM #NEW_CANCELADOS t1
      GROUP BY t1.LLAVE_PROD;

SELECT DISTINCT t1.SBU, 
                t1.RAMO_PROD
INTO #QUERY_FOR_NEW_CORE
FROM #NEW_CORE t1;


SELECT DISTINCT t1.SBU
INTO #QUERY_FOR_NEW_CORE_0000
FROM #NEW_CORE t1;

SELECT DISTINCT t1.SBU
INTO #QUERY_FOR_BASE_MARCA_2_0000
FROM #BASE_MARCA_2 t1;


SELECT DISTINCT 
          t1.RAMO_PROD, 
          t1.POLIZA, 
		  T1.CERTIFICADO,
		  T1.DOCUMENTO,
		  T1.TIPO_TRANSAC,
		  T1.TIPO_POLIZA,
          /* LLAVE_PROD */
             CONCAT(RAMO_PROD,'_', POLIZA,'_',CERTIFICADO) AS LLAVE_PROD, 
          /* LLAVE_COD */
            CONCAT(ramo_prod,'_',cod_producto) AS LLAVE_COD,
            CONCAT(ramo_prod,'_',TIPO_POLIZA) AS LLAVE_TIPO
INTO #VENCIMIENTOS
      FROM "PROD"."DWH_POLIZAS_H" t1
      WHERE t1.FF_certificado BETWEEN 20211030 AND 20211129
ORDER BY LLAVE_PROD, DOCUMENTO DESC ;





SELECT 
   RAMO_PROD, 
   POLIZA, 
   CERTIFICADO, 
   DOCUMENTO, 
   TIPO_TRANSAC,
   TIPO_POLIZA,
   LLAVE_PROD, 
   LLAVE_COD,
   LLAVE_TIPO,
   ROW_NUMBER() OVER(PARTITION BY LLAVE_PROD ORDER BY DOCUMENTO DESC) AS MARCAR_CANCEL,
   ROW_NUMBER() OVER(PARTITION BY LLAVE_PROD ORDER BY DOCUMENTO DESC) AS MARCAR_UNICA
INTO #VENCIMIENTOS_2
FROM #VENCIMIENTOS;


UPDATE #VENCIMIENTOS_2 SET MARCAR_CANCEL = CASE WHEN MARCAR_UNICA = 1 AND TIPO_TRANSAC = 4 THEN 1 ELSE NULL END;

UPDATE #VENCIMIENTOS_2 SET MARCAR_UNICA = CASE WHEN MARCAR_UNICA != 1 THEN NULL ELSE MARCAR_UNICA END;	  


SELECT t1.RAMO_PROD, 
          t1.POLIZA, 
		  T1.CERTIFICADO,
          t1.DOCUMENTO, 
          t1.TIPO_TRANSAC,
  		T1.LLAVE_TIPO, 
          t1.LLAVE_PROD, 
          t1.LLAVE_COD
INTO #VENCIMIENTOS_1
      FROM #VENCIMIENTOS_2 t1
      WHERE t1.MARCAR_UNICA = 1 AND t1.MARCAR_CANCEL IS NULL;


 SELECT DISTINCT 
          t1.RAMO_PROD, 
          t1.POLIZA, 
          T1.CERTIFICADO,
          /* LLAVE_PROD */
            CONCAT(RAMO_PROD,'_',POLIZA,'_',CERTIFICADO) AS LLAVE_PROD, 
          /* LLAVE_COD */
            CONCAT(ramo_prod,'_',cod_producto) AS LLAVE_COD,
			CONCAT(ramo_prod,'_',TIPO_POLIZA) AS LLAVE_TIPO
INTO #RENOVADOS
      FROM "PROD"."DWH_POLIZAS_H" t1
      WHERE t1.FI_certificado BETWEEN 20211030 AND 20211129  AND TIPO_TRANSAC=2 ;


SELECT 
          T1.LLAVE_COD, 
          t1.RAMO_PROD, 
          t1.POLIZA,
          T1.CERTIFICADO, 
          t1.LLAVE_PROD, 
		  t1.LLAVE_TIPO,
		  t2.APLICATIVO, 
          t2.SBU
INTO #VENCIMIENTOS_MARCA
      FROM #VENCIMIENTOS_1 t1
LEFT JOIN #RAMOS_PROD t2 ON (t1.RAMO_PROD=t2.RAMO_PROD);


SELECT * 
INTO #VENCIMIENTOS_MARCA_1
FROM #VENCIMIENTOS_MARCA;

UPDATE #VENCIMIENTOS_MARCA_1 SET SBU = '6400 - Bonds' WHERE LLAVE_COD = 'LB_1';


UPDATE #VENCIMIENTOS_MARCA_1 SET SBU = 'Individual Health, Dental, Disabi' WHERE LLAVE_TIPO IN ('ACS_I','ADU_I','CAN_I','CCP_I','E1_I','H1_I','O10_I','RDH_I','SE_I','T1_I','Z1_I','LMP_I');


SELECT 
          t1.RAMO_PROD, 
          t1.POLIZA,
          T1.CERTIFICADO, 
          t1.LLAVE_PROD,
          t1.LLAVE_TIPO, 
          t1.APLICATIVO, 
          t1.SBU
INTO #VENCIMIENTOS_MARCA_2
      FROM #VENCIMIENTOS_MARCA_1 t1
      WHERE t1.APLICATIVO  IS NOT NULL;
	  

SELECT  
          t1.RAMO_PROD, 
          t1.POLIZA,
		  T1.CERTIFICADO,
          t1.LLAVE_PROD, 
          t1.APLICATIVO,
          t1.LLAVE_TIPO, 
          t1.SBU,
		  T2.LLAVE_PROD AS RENOVADO
INTO #VENCIDOS_RENOVADOS
FROM #VENCIMIENTOS_MARCA_2 t1
LEFT JOIN  #RENOVADOS t2 ON (T1.LLAVE_PROD=T2.LLAVE_PROD) 

SELECT t1.LLAVE_PROD, 
          /* COUNT_of_LLAVE_PROD */
        (COUNT(t1.LLAVE_PROD)) AS COUNT_of_LLAVE_PROD
INTO #QUERY1
FROM #RENOVADOS t1
GROUP BY t1.LLAVE_PROD;


SELECT DISTINCT t1.RAMO_PROD
INTO #QUERY_FOR_VENCIMIENTOS_MARCA
      FROM #VENCIMIENTOS_MARCA t1
      WHERE t1.SBU IS NULL;
	  
SELECT t1.SBU, 
          /* COUNT_DISTINCT_of_LLAVE_PROD */
            (COUNT(DISTINCT(t1.LLAVE_PROD))) AS COUNT_DISTINCT_of_LLAVE_PROD
INTO #QUERY_FOR_VENCIDOS_RENOVADOS
FROM #VENCIDOS_RENOVADOS t1
WHERE t1.RENOVADO IS NULL AND t1.SBU IN 
           (
           '7110 - Group Life',
           '7120 - Group Health, Dental, Disability',
           '8600 - Personal Accident',
           'Individual Health, Dental, Disabi'
           )
      GROUP BY t1.SBU;


  
SELECT t1.SBU, 
          /* COUNT_DISTINCT_of_LLAVE_PROD */
            (COUNT(DISTINCT(t1.LLAVE_PROD))) AS COUNT_DISTINCT_of_LLAVE_PROD
INTO #QUERY_FOR_VENCIDOS_RENOVADO_0000
      FROM #VENCIDOS_RENOVADOS t1
      WHERE t1.RENOVADO IS NOT NULL
      GROUP BY t1.SBU;


SELECT t1.LLAVE_PROD, 
          /* COUNT_of_LLAVE_PROD */
            (COUNT(t1.LLAVE_PROD)) AS COUNT_of_LLAVE_PROD
INTO #QUERY_FOR_VENCIDOS_RENOVADO_0001
      FROM #VENCIDOS_RENOVADOS t1
      GROUP BY t1.LLAVE_PROD;
	  
	  
SELECT * FROM #QUERY_FOR_VENCIDOS_RENOVADOS

select * from #QUERY_FOR_VENCIDOS_RENOVADO_0000

SELECT * FROM #QUERY_FOR_VENCIDOS_RENOVADO_0001



/* 
Developed By:
https://github.com/metalhead13
*/